- .circleci/config.yml
By caching `node_modules` but not the stuff that is in `~/.cache`, we end up without a Cypress binary, so re-running builds with the cache fails (e.g: https://circleci.com/gh/percy/percy-cypress/53).
(Btw, reading the Cypress docs on this, they recommend that folks don't cache `node_modules` at all, and also using `npm ci` instead of `npm install`. I haven't made those changes, but let me know if you'd like me to. Docs are here: https://docs.cypress.io/guides/guides/continuous-integration.html#Caching)
@djones for review
> Cache the Cypress binary (fixes broken CI master build)

- .circleci/config.yml
Verified that re-rerunning works (i.e. no caching problems): https://circleci.com/gh/percy/percy-cypress/tree/update-ci
> Use npm ci on CircleCI, and cache ~/.npm instead of node_modules

- cypress.json
- cypress/integration/sdk_spec.js
- cypress/plugins/index.js
- lib/index.ts
- package-lock.json
- package.json
- percy-healthcheck
This PR also re-enables `chromeWebSecurity`, since this change allow us to circumvent CSP issues when snapshotting.
This PR depends on the changes in https://github.com/percy/percy-agent/pull/52 to work.
> Change SDK to send DOM snapshot POST request directly to Percy Agent service

- package.json
This should make our release process more robust, as well (makes it harder to release old files, which we discovered has happened at least once).
> Add 'clean' script to blow away compiled JS files, and run it before building

- lib/index.ts
- lib/percy-healthcheck
- package-lock.json
- package.json
- run-tests.js
The main change here is getting away from trying to rely on `node` to find the path to a `bin` we install, and instead try to compute the full path to the `percy-healthcheck` script ourselves, in a way similar to how we do that for `percy-agent.js`.
This change also adds some additional logging that should help in the case when the healthcheck fails. 
I did not succeed in doing a magic `npm link` before calling the tests, so that in the package tests we can rely on `@percy/cypress` being installed, so I'm still falling back on the somewhat ugly option of manually copying stuff into `node_modules` before the tests run. Since this is just for development (for the tests in this package), I think that's ok.
@Robdel12 @djones for review
> Find and use full path to percy-healthcheck script

- cypress/integration/sdk_spec.js
- lib/index.ts
Percy agent accepts a `domTransformation` option in its constructor, but currently our cypress sdk is not passing it into the right place. It is currently passing it into the `percySnapshot` method, where it should be passed to the `percyAgent` `constructor` method. This PR passes it to the constructor method.
> Pass `domTransformation` option to PercyAgent constructor

- lib/index.ts
When working on #73, I forgot to remove this import which is no longer used.
> chore: Remove unneeded `path` import

- package.json
This is needed because the caret (`^`) "allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple": https://github.com/npm/node-semver#caret-ranges-123-025-004
This means `^0.2.2` will only ever update if we release more `0.2.x` releases, but nothing higher.
We can use the tilde to open the range up more _until_ we hit 1.x for `@percy/agent`. More information about the semver tilde: https://github.com/npm/node-semver#tilde-ranges-123-12-1
> fix: Open `@percy/agent` version range (tilde over caret)

- .gitignore
- cypress/plugins/index.js
- lib/index.ts
- lib/task.ts
- package.json
- task.js
BREAKING CHANGE:
In all of the Percy SDKs we do a thing called a "heath check", which makes sure the Percy agent server is open and ready to accept the DOM we're going to `POST` to it. If the health check fails, we will disable Percy in the SDK so we're not failing your tests due to Percy not running. 
In the Cypress SDK, this was implemented in an interesting way due a limitation with `cy.request`.  The TL:DR of that is we can't `.catch` a failed request, so we needed to use `cy.exec` to health check & gracefully fall out. You can read a little more about that limitation here: https://github.com/cypress-io/cypress/issues/3161
`cy.exec` has it's own issues, which are outlined here: #104 This is a major blocker for _a lot_ of customers. 
This will fix #104 (and hopefully #138).
`cy.task` …
> fix: Use `cy.task` for health check rather than `cy.exec` (BREAKING CHANGE)

- index.d.ts
I forgot to update the types file when we added `percyCSS`. This closes #155
> fix: add `percyCSS` option to types

- index.d.ts
- lib/index.ts
Adds the `requestHeaders` option for agent so we can pass request headers for asset-discovery.
> feat: Add request headers option for asset-discovery

- package.json
This will close #193
(We're fully compatible, this will suppress any warnings/errors on install)
> fix: Update peerDependencies for Cypress v4

- package.json
We have been happily using with Cypress 5 for several months, this removes the warning when running yarn that it is incompatible.
> fix: Add cypress 5 to peerDependencies

- package.json
> fix: Update Cypress `peerDependency` for Cypress 6

- .github/release-drafter.yml
- .github/workflows/release.yml
- README.md
- package.json
Prepares for v3 release by removing prerelease references and adding `@percy/migrate` instructions to the readme.
> 🔧 Prepare for v3

- cypress/integration/index.test.js
- index.js
- yarn.lock
Percy is designed (at this time) to run in CI, with one complete test run to each build. Running Percy when doing TDD style tests (or anything watching changes like `cypress open`) will result in duplicate snapshot errors/unexpected results. 
On top of that, a recent bug in the Cypress networking layer (likely https://github.com/cypress-io/cypress/issues/15101) causes any tests that call `cy.percySnapshot` to hang/break (since we make a network request, which eventually causes that callstack error in Cypress). 
Since Percy's workflow is already misaligned with using `cypress open`, we're going to disable Percy from running / making network calls in Cypress Interactive mode. This could result in empty builds, which will eventually be handled upstream in `@percy/core` when we implement a …
> ✨  Disable Percy when Cypress is in interactive mode

- index.js
Assets that take a long time to respond in asset discovery can cause the `cy.then` promise to timeout. We _must_ wait for all assets to be discovered/resolved/captured before moving onto the next test, or we risk capturing the wrong asset for that given snapshot. For example, if the server shuts down after each test, we would fail to capture those assets if we didn't await on asset discovery to finish (resulting in broken snapshots).
With that said, we can safely increase this timeout beyond asset discoveries timeout since asset discovery will timeout first.
> 🐛  Increase timeout to 1.5x the asset discovery timeout (30s)

- cypress/e2e/index.cy.js
- package.json
- yarn.lock
This PR updates tests to utilize CLI's new testing mode and updated `@percy/sdk-utils` test helpers.
> ✅ Use Percy CLI testing mode for tests

- cypress/e2e/index.cy.js
- package.json
- yarn.lock
This updates the SDKs `@percy/sdk-utils` new logger mocking since the remote logger has been removed.
> ⬆️ Upgrade tests to latest `@percy/sdk-utils` for logger mocking

- README.md
- cypress/e2e/index.cy.js
- index.js
- types/index.d.ts
adding support for PERCY_THROW_ERROR_ON_FAILURE, by default it will be false.
percyThrowErrorOnFailure is to be set in cypress config.
> adding support for percyThrowErrorOnFailure , by default it will be false

- index.js
The new syntax for OR operator `name ||= cy.state('runnable').fullTitle();` is not supported and gives error. 
Reverted the syntax for this to initial one i.e `name = name || cy.state('runnable').fullTitle();`
> Changed OR operator to old syntax
